/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "GREEN_LED_aliases.h"
#include "GREEN_LED.h"
#include "YELLOW_LED_aliases.h"
#include "YELLOW_LED.h"
#include "RED_LED_aliases.h"
#include "RED_LED.h"
#include "UART_LOG.h"
#include "ErikaOS_ee.h"
#include "ErikaOS_ee_tracing.h"
#include "SEVEN_reg.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_G_aliases.h"
#include "SEVEN_G.h"
#include "SEVEN_F_aliases.h"
#include "SEVEN_F.h"
#include "SEVEN_E_aliases.h"
#include "SEVEN_E.h"
#include "SEVEN_D_aliases.h"
#include "SEVEN_D.h"
#include "SEVEN_C_aliases.h"
#include "SEVEN_C.h"
#include "SEVEN_B_aliases.h"
#include "SEVEN_B.h"
#include "SEVEN_A_aliases.h"
#include "SEVEN_A.h"
#include "ButtonRight_aliases.h"
#include "ButtonRight.h"
#include "ButtonLeft_aliases.h"
#include "ButtonLeft.h"
#include "TFT_SPI.h"
#include "TFT_SPI_PVT.h"
#include "TFT_SCL_aliases.h"
#include "TFT_SCL.h"
#include "TFT_DC_aliases.h"
#include "TFT_DC.h"
#include "TFT_RES_aliases.h"
#include "TFT_RES.h"
#include "TFT_CS_aliases.h"
#include "TFT_CS.h"
#include "TFT_LED_aliases.h"
#include "TFT_LED.h"
#include "TFT_SDA_aliases.h"
#include "TFT_SDA.h"
#include "TFT_BackLight.h"
#include "CLK_LED.h"
#include "isr_button.h"
#include "UART_LOG_IntClock.h"
#include "TFT_SPI_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

